[pytest]
addopts = -ra --import-mode=importlib
testpaths =
    src/ferox_audio_sim/test
    src/ferox_audio_g1/test
    src/ferox_audio_go2/test
pythonpath =
    src/ferox_audio_sim
    src/ferox_audio_g1
    src/ferox_audio_go2
